name: firebase3
description: Dart wrapper library for the new Firebase.
version: 0.2.1-dev
author: Jana Moudra <jana.moudra@gmail.com>
homepage: https://github.com/Janamou/firebase3-dart

environment:
  sdk: '>=1.18.0 <2.0.0'

dependencies:
  js: ">=0.6.0 <0.7.0"
  func: ">=0.1.0 <0.2.0"
  browser: '>=0.10.0 <0.11.0'

dev_dependencies:
  http: '^0.11.3'
  path: '^1.3.9'
  test: '>=0.12.0 <0.13.0'
