name: firebase
description: Firebase libraries for Dart on the web and server
version: 9.0.1-dev
repository: https://github.com/FirebaseExtended/firebase-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  js: ^0.6.3

dev_dependencies:
  _shared_assets:
    path: ../_shared_assets
  build_runner: ^1.0.0
  build_test: ^2.0.0
  build_web_compilers: ^2.0.0
  googleapis_auth: ^1.0.0
  path: ^1.3.9
  pedantic: ^1.3.0
  test: ^1.16.0
